### ISSUE TITLE
time_est issue

### ISSUE THREAD

**Issue by bardcsl** [bardcsl/Continuous_Monitoring#1]
Hey Owen, something I just noticed--

When you write the purpleairc dataframe to a csv file, the time_est column is just a duiplicate of the time_utc column. ITs particularly strange because the purpleairc dataframe has the correctly converted times in the tim_est column down to the last step of exporting to csv. Do you think its an excel issue?

**Comment by bardcsl** [comment]
nvm, I fixed it. But I needed to convert time_est to a character column in the script. We may need to add that in

**Comment by oroconnor** [comment]
Ok. I will look into it!

**Comment by oroconnor** [comment]
Yikes. I'm not sure why that's happening. I agree with you, it keeps the datetime columns separate until it writes to csv file, and then messes them up. Not cool. Anyway, I put in the code for converting to chr format before saving. 
This sort of thing is part of why I also having it saving to the feather files. The idea of a feather file is that it saves the data in the same data format as your data frame. That way you are not dealing with saving to csv file, which strips your data of whatever datatypes you've assigned them to while working on your data frame. And then parsing the datatypes again when you read the csv file back in. Closing this issue because we have at least a temporary fix to the issue.
